export function deterministicCheckoutArtifact() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>PromptGolf Generated Checkout</title>
  <style>
    :root{color-scheme:dark;--bg:#101117;--panel:#181b23;--ink:#f8fafc;--muted:#a7b0c0;--line:#303644;--ok:#61d394;--bad:#ff7777;--warn:#f9c74f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#25213b,transparent 38rem),var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,sans-serif}.wrap{max-width:1040px;margin:0 auto;padding:28px}.grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(290px,.65fr);gap:18px}.panel{border:1px solid var(--line);border-radius:16px;background:color-mix(in srgb,var(--panel),transparent 3%);padding:18px}h1{font-size:32px;letter-spacing:-.03em;margin:0 0 6px}p{color:var(--muted);line-height:1.55}.item{display:grid;grid-template-columns:1fr auto;gap:14px;border-top:1px solid var(--line);padding:14px 0}.qty{display:flex;align-items:center;gap:8px}.qty button,.primary,.promo button{min-height:44px;border:0;border-radius:999px;padding:0 16px;font-weight:700;cursor:pointer}.qty button{width:44px;background:#252a36;color:var(--ink)}button:disabled{opacity:.55;cursor:not-allowed}.primary{width:100%;background:var(--ink);color:#07080b}.promo{display:flex;gap:8px;margin:14px 0}.promo input{min-height:44px;min-width:0;flex:1;border:1px solid var(--line);border-radius:12px;background:#10131b;color:var(--ink);padding:0 12px}.promo button{background:#2b3242;color:var(--ink)}.row{display:flex;justify-content:space-between;border-top:1px solid var(--line);padding:10px 0}.total{font-size:22px;font-weight:800}.error{color:var(--bad)}.success{color:var(--ok)}.notice{color:var(--warn)}@media(max-width:760px){.wrap{padding:16px}.grid{grid-template-columns:1fr}h1{font-size:26px}.item{grid-template-columns:1fr}.promo{flex-direction:column}.promo button{width:100%}} 
  </style>
</head>
<body>
  <main class="wrap">
    <h1>Generated checkout</h1>
    <p>Integer-cents demo app generated by PromptGolf stub mode. Promo codes: SAVE10, FREESHIP, BIGSAVE.</p>
    <div class="grid">
      <section class="panel" aria-labelledby="cart-title">
        <h2 id="cart-title">Cart items</h2>
        <div id="items"></div>
      </section>
      <aside class="panel" aria-labelledby="summary-title">
        <h2 id="summary-title">Order summary</h2>
        <label for="promo">Promo code</label>
        <div class="promo"><input id="promo" data-testid="promo-input" autocomplete="off" /><button data-testid="apply-promo">Apply</button></div>
        <p id="message" role="status" aria-live="polite"></p>
        <div class="row"><span>Subtotal</span><strong data-testid="subtotal"></strong></div>
        <div class="row"><span>Discount</span><strong data-testid="discount"></strong></div>
        <div class="row"><span>Shipping</span><strong data-testid="shipping"></strong></div>
        <div class="row"><span>Tax</span><strong data-testid="tax"></strong></div>
        <div class="row total"><span>Total</span><strong data-testid="total"></strong></div>
        <button class="primary" data-testid="checkout" style="margin-top:14px">Confirm order</button>
        <p id="confirmation" data-testid="confirmation" role="status"></p>
      </aside>
    </div>
  </main>
  <script>
    const fmt = c => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
    const cart = [{id:'bag',name:'Canvas tote',price:2500,qty:2,stock:3},{id:'beans',name:'Espresso beans',price:1800,qty:1,stock:4},{id:'mug',name:'Stoneware mug',price:1200,qty:0,stock:0}];
    let discount = 0, applied = '', submitting = false;
    const els = {items:document.getElementById('items'),msg:document.getElementById('message'),confirm:document.getElementById('confirmation')};
    function subtotal(){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
    function shipping(){return subtotal() >= 5000 || applied === 'FREESHIP' ? 0 : 799}
    function tax(){return Math.round(Math.max(0, subtotal()-discount)*0.0825)}
    function total(){return Math.max(0, subtotal()-discount)+shipping()+tax()}
    function render(){
      els.items.innerHTML = cart.map(i=>'<article class="item" data-testid="item-'+i.id+'"><div><h3>'+i.name+'</h3><p>'+fmt(i.price)+' · Stock '+i.stock+(i.stock===0?' · Out of stock':'')+'</p></div><div class="qty"><button aria-label="Decrease '+i.name+'" data-dec="'+i.id+'" '+(i.qty<=0?'disabled':'')+'>−</button><strong data-testid="qty-'+i.id+'">'+i.qty+'</strong><button aria-label="Increase '+i.name+'" data-inc="'+i.id+'" '+(i.qty>=i.stock?'disabled':'')+'>+</button></div></article>').join('');
      document.querySelector('[data-testid=subtotal]').textContent=fmt(subtotal()); document.querySelector('[data-testid=discount]').textContent='-'+fmt(discount); document.querySelector('[data-testid=shipping]').textContent=fmt(shipping()); document.querySelector('[data-testid=tax]').textContent=fmt(tax()); document.querySelector('[data-testid=total]').textContent=fmt(total());
    }
    document.addEventListener('click', e=>{const id=e.target.dataset.inc||e.target.dataset.dec;if(id){const item=cart.find(x=>x.id===id); if(e.target.dataset.inc && item.qty<item.stock)item.qty++; if(e.target.dataset.dec && item.qty>0)item.qty--; render();}});
    document.querySelector('[data-testid=apply-promo]').onclick=()=>{const code=document.querySelector('[data-testid=promo-input]').value.trim().toUpperCase(); els.msg.className=''; if(code==='SAVE10'){applied=code; discount=Math.min(subtotal(),Math.round(subtotal()*0.10)); els.msg.textContent='SAVE10 applied.'; els.msg.className='success'} else if(code==='FREESHIP'){applied=code; discount=0; els.msg.textContent='Free shipping applied.'; els.msg.className='success'} else if(code==='BIGSAVE'){applied=code; discount=subtotal(); els.msg.textContent='Maximum discount applied without negative totals.'; els.msg.className='success'} else {applied=''; discount=0; els.msg.textContent='Invalid promo code. Try SAVE10.'; els.msg.className='error'} render();};
    document.querySelector('[data-testid=checkout]').onclick=async e=>{ if(submitting)return; els.confirm.textContent=''; if(cart.some(i=>i.stock===0 && i.qty>0)){els.confirm.textContent='Remove out-of-stock items before checkout.'; els.confirm.className='error'; return;} submitting=true; e.target.disabled=true; e.target.textContent='Submitting…'; els.confirm.textContent='Submitting order…'; await new Promise(r=>setTimeout(r,250)); els.confirm.textContent='Order confirmed - one confirmation created.'; els.confirm.className='success'; e.target.textContent='Order confirmed'; render(); };
    render();
  </script>
</body>
</html>`;
}
